version: '3.8'
services:
  redis:
    container_name: tabnine-redis
    image: redis:7.0.4-alpine
    restart: always
    ports:
      - '6395:6379'
    volumes:
      - redis:/data
volumes:
  redis:
